[package]
name = "octmm"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.35", features = ["derive"] }
mlua = { version = "0.10", features = ["luau"] }
cpal = "0.16.0"
fundsp = "0.20.0"
